name: LaTeX compilation
on:
  push:
    branches:
      - main
      - fix/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Merge main branch
        run: |
          git config user.name sista05
          git config user.email akisista05@gmail.com

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file:
            sample.tex

      - name: Push PDF file
        run: |
          git add .
          git commit -m "LaTeX compilation"
          git push origin pdf